[package]
name = "ai-creatures"
version = "0.3.0"
description = "A tiny evolving creature that lives on your desktop"
authors = ["yecos"]
edition = "2021"

[lib]
name = "ai_creatures_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
